(require 'el-get-core) ;; for `el-get-executable-find`
(defvar cfg:tmp-dir)
(when (el-get-executable-find "w3m")
  (require 'w3m-load)
  (autoload 'w3m "w3m" "Interface for w3m on Emacs." t)
  (custom-set-variables
   '(w3m-use-tab t)
   `(w3m-arrived-file ,(concat cfg:tmp-dir "w3m-arrived"))
   `(w3m-cookie-file ,(concat cfg:tmp-dir "w3m-cookie"))
   `(w3m-form-textarea-directory ,(concat cfg:tmp-dir "w3m-textarea"))
   `(w3m-bookmark-file ,(concat cfg:tmp-dir "w3m-bookmark")))
  (eval-when-compile (require 'w3m))
  (defun w3m-google-search (word)
    (interactive "sSearch Word: ")
    (w3m-browse-url (concat "http://www.google.co.jp/search?hl=ja&q=" word)))
  (global-set-key (kbd "C-<f3>") 'w3m-google-search)
  (defun w3m-alc-search (word)
    (interactive "sSearch Word: ")
    (w3m-browse-url (concat "http://eow.alc.co.jp/search?q=" word)))
  (global-set-key (kbd "C-<f4>") 'w3m-alc-search))
