(when (display-graphic-p)
  (if (eq window-system 'ns)
      (defun my:toggle-frame-size () (interactive) (ns-toggle-fullscreen))
    (eval-and-compile (require 'maxframe))
    (defvar my:frame-max-flag nil)
    (defun my:toggle-frame-size ()
      (interactive)
      (if my:frame-max-flag
          (progn
            (restore-frame)
            (setq my:frame-max-flag nil))
        (maximize-frame)
        (setq my:frame-max-flag t))))
  (add-hook 'window-setup-hook 'my:toggle-frame-size t)
  (global-set-key [f11] 'my:toggle-frame-size))
